### ISSUE TITLE
considering the use of magic method __set , __unset , __isset , __get 

### ISSUE THREAD

**Issue by KTP95** [mwebbers/JSend#1]
so like here https://github.com/alexei/php-jsend/blob/master/JSend.php
this for alowed so like this

$success = Jsend::success($data);
$success->myvar = 'hello world jsend';
$success->respond();

**Comment by mwebbers** [comment]
@KTP95 i totally missed your ticket, sorry. We made a simple wrapper to have an easy way to create a valid JSend object. The wrapper class is initially not a model, but we might add some kind of functionality to manage the JSend data in a future.
