### ISSUE TITLE
Setting Content-Type headers

### ISSUE THREAD

**Issue by mrchimp** [mwebbers/JSend#2]
Thanks for this package. it's pretty neat but I've got an issue with it...

I see that there is a `->send()` method that sets the headers but I can't work out how I'm supposed to use it.

This sends the right response but doesn't set the headers:

        return JSend::success([
            'product_categories' => $products,
        ]);

Same with this:

        return JSend::success([
            'product_categories' => $products,
        ])->send();

This is the only way I can get it to work correctly, and this doesn't feel all that elegant.

        return response()->json(JSend::success([
            'product_categories' => $products,
        ])->toArray());

**Comment by mwebbers** [comment]
@mrchimp The JSend->send(); method is just a simple helper method to send the JSend model if you are use a simple script. It basically does this.

```
header('Content-Type: application/json');
echo (string) $this;
```

Which header is not set?

**Comment by mrchimp** [comment]
Oh, forgive me. I must have made a mistake. The following works as expected and `Content-Type` header _is_ set:

    return JSend::success([
        'product_categories' => $products,
    ])->send();
